### PR TITLE
Fix activation on pools that have a mountpoint

### LINKED ISSUE #511: Activation fails on newly setup host
```python-traceback
root@tutorial:/usr/local/src/libiocage # ioc list
Log directory '/var/log/iocage' created
iocage is not activated yet - please run `ioc activate <POOL>` first and select a pool
root@tutorial:/usr/local/src/libiocage # ioc activate zroot
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ioc/activate.py", line 66, in cli
    mountpoint=mountpoint
  File "/usr/local/lib/python3.6/site-packages/iocage/Datasets.py", line 362, in activate_pool
    self.attach_source("iocage", f"{pool.name}/iocage")
  File "/usr/local/lib/python3.6/site-packages/iocage/Datasets.py", line 262, in attach_source
    logger=self.logger
  File "/usr/local/lib/python3.6/site-packages/iocage/Datasets.py", line 101, in __init__
    if self.root.mountpoint is None:
AttributeError: 'RootDatasets' object has no attribute 'root'
```

### PR DESCRIPTION
**Pull request by gronke**
fixes #511

- Always attempt to claim /iocage for the (first) activated pool
- If the pool has no mountpoint and `/iocage` is existing, activation fails. Otherwise the mountpoint is automatically selected.

The regression was introduced in PR #502

### CODE REVIEW

File: iocage/Datasets.py [hunk 1]
```diff
@@ -80,23 +80,27 @@ def __init__(
                 pool_mountpoint = self.zfs.get_dataset(
                     self.zfs.get_pool(root_dataset).name
                 ).mountpoint
+                preferred_mountpoint = "/iocage"
+                preferred_mountpoint_exists = os.path.ismount(preferred_mountpoint
+                ) is True
```
Comment (igalic) [inline iocage/Datasets.py]: what's up with this indentation?

Comment (igalic) [reply iocage/Datasets.py]: also: `_exists` is ambigious, we only really care about whether it's `_inuse`
